id: IFF67E75B
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T06:26:47+00:00'
last_modified: '2022-06-08T14:14:29.272848+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG13981
  title: ལེགས་བཤད་བསྟན་བཅོས་ཕྱོགས་བསྒྲིགས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '9526':
      image_group_id: I1KG13983
      title: ''
      total_pages: 422
      order: 1
      base_file: 9526.txt
    E49C:
      image_group_id: I1KG13984
      title: ''
      total_pages: 520
      order: 2
      base_file: E49C.txt
    58E0:
      image_group_id: I1KG13985
      title: ''
      total_pages: 286
      order: 3
      base_file: 58E0.txt
    8B1C:
      image_group_id: I1KG13986
      title: ''
      total_pages: 248
      order: 4
      base_file: 8B1C.txt
    1D82:
      image_group_id: I1KG13987
      title: ''
      total_pages: 336
      order: 5
      base_file: 1D82.txt
    9F4C:
      image_group_id: I1KG13988
      title: ''
      total_pages: 304
      order: 6
      base_file: 9F4C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
